### PR TITLE
Auto News Consumer

### PR DESCRIPTION
**Pull request by harrygillingham99**
### What ya done?
- Added a new HostedService cron job which will auto-consume news from an API and add to the Alerts DB.
- Use ReSharper to clean up all the crap

### CODE REVIEW

**Comment by harrygillingham99** [comment]
This is what I have so far, you'll need to grab a news api key

**Comment by WilliamJenner** [comment]
I'll approve, remind me to do secrets on the server

**Comment by WilliamJenner** [comment]
Oop, it's still a draft. Sort it in the morning.

**Comment by harrygillingham99** [comment]
ayyyy enjoy some good auto news

**Pull request merged**
